services:
  # Backend service
  backend:
    build: ./backend
    container_name: spa-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - METRICS_API_KEY=${METRICS_API_KEY}
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    networks:
      - spa-network

  # Frontend service
  frontend:
    build: ./frontend
    container_name: spa-frontend
    restart: always
    ports:
      - "8080:80"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    networks:
      - spa-network

  # Database service
  db:
    image: postgres:14-alpine
    container_name: spa-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - spa-network

networks:
  spa-network:
    driver: bridge

volumes:
  postgres_data: 
