[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "python backend/scripts/migrate_db.py && gunicorn --chdir backend app:app"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
FLASK_APP = "app.py"
FLASK_ENV = "production"
PORT = "5000" 