server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spa-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: spa-backend
          __path__: /var/log/spa/*.log
          
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            module: module
            function: function
            line: line
            request_id: request_id
            
      - labels:
          level:
          module:
          function:
          request_id:
          
      - timestamp:
          source: timestamp
          format: RFC3339
          
      - output:
          source: message 