global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'spa-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:5000']
    bearer_token: '${METRICS_API_KEY}'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - 'alerts.yml' 